spring:
  jpa:
    hibernate:
      ddl-auto: none # validate
    #defer-datasource-initialization: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gitrdfdb}
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD:example} # temporary for prototyping

server:
  port: 8080 # env SERVER_PORT can be used to set server port from outside via env variable -> set to 8080, because we can usually rely on docker networking